spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL

  jpa:
    hibernate:
      ddl-auto: create-drop

logging.level:
  org.hibernate.tool.hbm2ddl: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE